# Generated by Django 6.0.2 on 2026-02-19 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("measurement", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="measurement",
            old_name="date_time",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="measurement",
            old_name="sensor_id",
            new_name="measurement",
        ),
    ]
