# Generated by Django 6.0.2 on 2026-02-19 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("measurement", "0002_rename_date_time_measurement_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="measurement",
            old_name="measurement",
            new_name="sensor",
        ),
    ]
